### ISSUE TITLE
Cant scroll window after opening VAE Details

### ISSUE THREAD

**Issue by RedCardinal** [xnought/vae-explainer#1]
Chrome 129.0.6668.60 (Official Build) (64-bit) on Win 11
4k monitor running @2x (1080p), which may be key to issue.

1. Load https://xnought.github.io/vae-explainer/
2. Click on "Explain VAE Details"
3. Content in 2 lower `<foreignObject>` overflow off bottom of screen.  No scrolling possible.

![image](https://github.com/user-attachments/assets/b5d69c95-9776-47cb-9181-cd88133386a0)

**Comment by xnought** [comment]
Thank you for the detailed issue. Just added scroll + added the right code font.
